const $=id=>document.getElementById(id),num=v=>Number(v).toLocaleString('zh-CN'),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let session=null,run=null,meta=null,summary=null,tab='Sheet4-汇总表',page=1,total=0,busy=false,dirty=false,tableRequest=0;
const headers={Sheet1:['一卡通号','学号','姓名','学院','年级','餐饮次数 ↓','总额（元）','笔均（元）','消费天数','日均（元）'],Sheet2:['一卡通号','学号','姓名','学院','年级','饮品次数 ↑','总额（元）','消费天数','日均（元）','笔均（元）'],Sheet3:['一卡通号','学号','姓名','学院','年级','商服总额（元）↑','商服次数','超市金额（元）'],'Sheet4-汇总表':['一卡通号','学号','姓名','学院','年级','餐饮次数','餐饮总额','饮品次数','饮品总额','商服总额','超市金额']};
const worker=new Worker('./worker.js?v=3.1.0');let requestId=0;const pending=new Map();let downloadUrls=[];
worker.onmessage=({data:d})=>{if(d.progress){$('progressText').textContent=d.progress.stage+(d.progress.rows?' · 已读取 '+num(d.progress.rows)+' 条':'')+'，请稍候';return;}const p=pending.get(d.id);if(!p)return;pending.delete(d.id);d.error?p.reject(new Error(d.error)):p.resolve(d.bytes?d:d.data);};
worker.onerror=()=>{for(const p of pending.values())p.reject(new Error('计算组件未能运行，请使用最新版桌面 Chrome 或 Edge 浏览器重新打开。'));pending.clear();};
function request(message,transfer=[]){return new Promise((resolve,reject)=>{const id=++requestId;pending.set(id,{resolve,reject});worker.postMessage({id,...message},transfer);});}
async function api(url,options={}){if(options.body instanceof File){const f=options.body;if(!f.name.toLowerCase().endsWith('.xlsx'))throw new Error('请选择 .xlsx 文件');if(!f.size||f.size>150*1024*1024)throw new Error('请选择不超过150MB的有效文件');const buffer=await f.arrayBuffer();return request({url,filename:f.name,buffer},[buffer]);}return request({url,payload:options.body?JSON.parse(options.body):{}});}
async function refreshDownloads(){for(const u of downloadUrls)URL.revokeObjectURL(u);downloadUrls=[];for(const [kind,id] of [['xlsx','downloadXlsx'],['zip','downloadZip']]){const d=await request({download:kind});const url=URL.createObjectURL(new Blob([d.bytes],{type:kind==='xlsx'?'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':'application/zip'}));downloadUrls.push(url);$(id).href=url;$(id).download=d.name;}}
window.addEventListener('beforeunload',e=>{if(session||busy){e.preventDefault();e.returnValue='';}});

function fail(e){$('error').textContent=e.message||String(e);$('error').hidden=false;}
function setBusy(v,message=''){busy=v;$('upload').disabled=v;$('source').disabled=v;$('month').disabled=v||!session;$('analyze').disabled=v||!session;$('analyzeAll').disabled=v||!session;$('rosterBtn').disabled=v||!session;$('progress').hidden=!v;$('progressText').textContent=message;document.querySelectorAll('#rules input,#rules select,#mapping select,#supermarkets').forEach(e=>e.disabled=v);}
function stale(){$('downloadAll').hidden=true;if(run){dirty=true;$('stale').hidden=false;document.querySelectorAll('.downloads a').forEach(e=>e.classList.add('disabled'));}}

function applyMeta(m,preferred){meta=m;const months=Object.keys(m.months);$('month').innerHTML=months.map(x=>`<option value="${x}">${x}　${num(m.months[x])} 条</option>`).join('');$('month').value=preferred&&months.includes(preferred)?preferred:months[0];$('sourceInfo').textContent=m.source_name+' · '+num(m.counts.input_rows)+' 条 · '+m.date_start+' 至 '+m.date_end;$('mappingBox').hidden=false;updateMonth();}
function updateMonth(){if(!meta)return;const month=$('month').value;const cats=Object.values(meta.categories.reduce((a,x)=>{a[x.category]??={category:x.category,rows:0};a[x.category].rows+=x.rows;return a;},{}));const defaults={'学生食堂餐饮类（餐饮）':'餐饮','学生食堂饮品水果类（饮品）':'饮品','商服及浴池相关类（商服）':'商服','学生食堂餐饮类':'餐饮','学生食堂饮品水果类':'饮品','商服及浴池相关类':'商服','餐饮':'餐饮','饮品':'饮品','商服':'商服'};$('mapping').innerHTML=cats.map(x=>`<label>${esc(x.category||'空分类')} · ${num(x.rows)}条（全文件）<select data-category="${esc(x.category)}">${['请选择','餐饮','饮品','商服','忽略'].map(t=>`<option ${t===(defaults[x.category]||'请选择')?'selected':''}>${t}</option>`).join('')}</select></label>`).join('');const merchants=meta.merchants.filter(x=>x.month===month);$('supermarkets').innerHTML=[...new Set(merchants.filter(x=>defaults[x.category]==='商服').map(x=>x.merchant))].map(x=>`<option value="${esc(x)}" ${x.includes('超市')?'selected':''}>${esc(x)}</option>`).join('');$('dataNotes').hidden=false;const errors=meta.counts.invalid_rows||0;$('dataNotes').textContent=`按真实日期选择 ${month}。全文件完全重复行 ${num(meta.counts.duplicate_rows||0)} 条，默认保留并在结果中报告当月数量。${errors?' 有 '+errors+' 条无效记录，涉及本月或日期不明时将阻止筛选。':''} 未上传名册时，学号、姓名、学院、年级留空。`;showMonthCheck();stale();}
$('month').addEventListener('change',updateMonth);
$('upload').onclick=async()=>{try{const f=$('source').files[0];if(!f)throw new Error('请先选择消费流水Excel');$('error').hidden=true;session=null;run=null;summary=null;meta=null;$('results').hidden=true;$('mappingBox').hidden=true;$('monthCheck').hidden=true;$('downloadAll').hidden=true;$('dataNotes').hidden=true;$('sourceInfo').textContent='正在读取新文件';setBusy(true,'正在浏览器中读取Excel');const j=await api('/api/upload?name='+encodeURIComponent(f.name),{method:'POST',body:f});const d=j;session=d.session;run=null;summary=null;$('results').hidden=true;applyMeta(d.meta);$('rosterInfo').textContent='';}catch(e){fail(e)}finally{setBusy(false)}};
$('rosterBtn').onclick=async()=>{try{const f=$('roster').files[0];if(!f)throw new Error('请先选择学生名册');setBusy(true,'正在匹配学生名册');const r=await api('/api/roster?session='+session+'&name='+encodeURIComponent(f.name),{method:'POST',body:f});$('rosterInfo').textContent='已载入 '+num(r.count)+' 个卡号；重新生成后生效。';stale();}catch(e){fail(e)}finally{setBusy(false)}};
function getRules(){const r={};for(const k of ['meal_count','meal_amount','drink_count','drink_amount','service_count','service_amount']){r[k]=Number($(k).value);if($(k).value===''||!Number.isFinite(r[k])||r[k]<0)throw new Error('请输入有效的非负阈值');}for(const k of ['deduplicate','extra_drink_average'])r[k]=$(k).checked;r.daily_basis=$('daily_basis').value;return r;}
$('analyze').onclick=async()=>{try{$('error').hidden=true;const rules=getRules(),mapping={};document.querySelectorAll('#mapping select').forEach(el=>mapping[el.dataset.category]=el.value);if(Object.values(mapping).includes('请选择'))throw new Error('请先设置全部消费场所类别的映射');const supermarkets=[...$('supermarkets').selectedOptions].map(o=>o.value);setBusy(true,'开始计算');const j=await api('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session,month:$('month').value,rules,mapping,supermarkets})});const d=j;run=d.run;summary=d.summary;await showResults();$('results').scrollIntoView({behavior:'smooth',block:'start'});}catch(e){fail(e)}finally{setBusy(false)}};
document.querySelectorAll('#rules input,#rules select').forEach(el=>el.addEventListener('change',stale));$('mapping').addEventListener('change',()=>{refreshSupermarkets();stale();});$('supermarkets').addEventListener('change',stale);
async function showResults(){dirty=false;$('stale').hidden=true;$('results').hidden=false;document.querySelectorAll('.downloads a').forEach(e=>e.classList.remove('disabled'));const s=summary;document.querySelectorAll('#mapping select').forEach(el=>{if(s.category_mapping[el.dataset.category])el.value=s.category_mapping[el.dataset.category];});refreshSupermarkets(s.supermarket_merchants);$('resultMonth').textContent=s.month+' / MONTHLY RESULT';$('allCount').textContent=num(s.card_count);$('selectedCount').textContent=num(s.selected_count);$('txnCount').textContent=num(Object.values(s.category_totals).reduce((a,x)=>a+x.count,0));$('matchCount').textContent=num(s.roster_matches);await refreshDownloads();$('resultNotes').innerHTML=`<p>本次结果：${esc(s.month)}，${esc(s.range[0])} 至 ${esc(s.range[1])}。重复行 ${s.duplicates} 条，${esc(s.duplicate_policy)}；日均按${s.rules.daily_basis==='active'?'该类别实际消费天数':'当月自然日'}计算。</p><p>三类表只列该类实际消费卡号；三表共有 ${num(s.three_table_cards)} 个卡号，再按六项条件筛选。${s.partial_month?' <strong>本月数据未覆盖整月日期范围，仍使用原月度阈值，未折算。</strong>':''}${s.supermarket_merchants.length?'超市子项包含：'+esc(s.supermarket_merchants.join('、')):'本月未识别到超市交易，0仅表示本次数据未观察到。'}${s.roster_matches<s.card_count?' 部分或全部身份字段未匹配名册。':''}</p>`;page=1;await loadTable();}
function format(v){return v===null||v===''?'<span class="empty">—</span>':typeof v==='boolean'?`<span class="${v?'pass':'fail'}">${v?'是':'否'}</span>`:typeof v==='number'?(Number.isInteger(v)?num(v):v.toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})):esc(v);}
async function loadTable(){if(!run)return;const request=++tableRequest;const d=await api(`/api/result?session=${session}&run=${run}&tab=${encodeURIComponent(tab)}&page=${page}&search=${encodeURIComponent($('search').value)}`);if(request!==tableRequest)return;total=d.total;let names=tab==='依据'?(d.rows[0]?Object.keys(d.rows[0]):['一卡通号','入选']):headers[tab];$('thead').innerHTML='<tr>'+names.map(n=>'<th>'+esc(n)+'</th>').join('')+'</tr>';$('tbody').innerHTML=d.rows.length?d.rows.map(row=>{const a=Array.isArray(row)?row:Object.values(row);return '<tr>'+a.map((v,i)=>`<td class="${typeof v==='number'?'num':''}">${i===0?`<button class="cardlink" data-card="${esc(v)}">${esc(v)}</button>`:format(v)}</td>`).join('')+'</tr>'}).join(''):`<tr><td colspan="${names.length}">没有符合当前条件的记录</td></tr>`;$('tableCaption').textContent=(tab==='Sheet4-汇总表'?'同时满足全部条件：':tab==='依据'?'全部卡号筛选依据：':'该类实际消费卡号：')+num(total)+' 个 · 点击卡号查看原始明细';$('pageInfo').textContent=`第 ${page} / ${Math.max(1,Math.ceil(total/50))} 页`;$('prev').disabled=page<=1;$('next').disabled=page*50>=total;}
document.querySelectorAll('[data-tab]').forEach(el=>el.onclick=()=>{tab=el.dataset.tab;page=1;document.querySelectorAll('[data-tab]').forEach(e=>e.classList.toggle('active',e===el));loadTable().catch(fail)});
let timer;$('search').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>{page=1;loadTable().catch(fail)},250)});$('prev').onclick=()=>{page--;loadTable().catch(fail)};$('next').onclick=()=>{page++;loadTable().catch(fail)};
$('tbody').onclick=async e=>{const b=e.target.closest('[data-card]');if(!b)return;try{const d=await api(`/api/trace?session=${session}&month=${summary.month}&card=${encodeURIComponent(b.dataset.card)}`);$('traceCaption').textContent=b.dataset.card+' · 共 '+num(d.total)+' 条，展示前500条。金额保留原始正负号；来源行号可用于查回Excel。'+(summary.rules.deduplicate?'本次筛选已排除标为重复的行。':'');$('traceTable').innerHTML='<thead><tr>'+['日期','类别','商户','交易额','完全重复行','来源表单','来源行号'].map(v=>'<th>'+v+'</th>').join('')+'</tr></thead><tbody>'+d.rows.map(r=>'<tr>'+[r.day,r.raw_category,r.merchant,(r.amount/100).toFixed(2),r.duplicate?'是':'否',r.source_sheet,r.source_row].map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>').join('')+'</tbody>';$('trace').showModal();}catch(e){fail(e)}};$('closeTrace').onclick=()=>$('trace').close();
(async()=>{try{setBusy(true,'正在准备计算组件');await api('/api/bootstrap');}catch(e){fail(e)}finally{setBusy(false)}})();

document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>document.querySelectorAll('nav a').forEach(x=>x.classList.toggle('active',x===a))));

function refreshSupermarkets(saved){
 if(!meta)return;
 const mapping={};document.querySelectorAll('#mapping select').forEach(el=>mapping[el.dataset.category]=el.value);
 const names=[...new Set(meta.merchants.filter(x=>x.month===$('month').value&&mapping[x.category]==='商服').map(x=>x.merchant))];
 const selected=saved===undefined?names.filter(x=>x.includes('超市')):saved;
 $('supermarkets').innerHTML=names.map(x=>`<option value="${esc(x)}" ${selected.includes(x)?'selected':''}>${esc(x)}</option>`).join('');
}

$('reset').onclick=()=>{if(confirm('清空本页的消费数据和结果？请先下载需要保留的结果。')){session=null;busy=false;worker.terminate();location.reload();}};
document.querySelectorAll('.downloads a').forEach(a=>a.addEventListener('click',e=>{if(dirty||busy)e.preventDefault();}));
try {document.modelContext?.registerTool({name:'read_screening_status',title:'读取月度筛选状态',description:'读取当前浏览器中已导入数据的月份与筛选结果数量，不返回学生身份或交易明细。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async input=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('此工具不接受参数');return {busy,imported:!!session,months:meta?Object.keys(meta.months):[],result:summary?{month:summary.month,cards:summary.card_count,selected:summary.selected_count,stale:dirty}:null};}});}catch{}

let allUrl=null;
function showMonthCheck(){const c=meta?.month_checks?.[$('month').value];$('monthCheck').hidden=!c;if(!c)return;$('monthCheck').innerHTML=`<strong>原始数据核对 · ${esc($('month').value)}</strong><p>${esc(c.range[0])} 至 ${esc(c.range[1])}${c.partial?' · 未覆盖整月日期范围，月度阈值不折算。':''}</p><div class="table-wrap"><table><thead><tr><th>原始消费场所类别</th><th>支出笔数</th><th>有消费的卡号</th><th>支出总额（元）</th></tr></thead><tbody>${c.categories.map(x=>`<tr><td>${esc(x.category)}</td><td>${num(x.count)}</td><td>${num(x.cards)}</td><td>${(x.cents/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}</td></tr>`).join('')}</tbody></table></div><p>以上为原始支出统计，含重复行。分类表只列该类实际消费记录；选择去重后，结果统计可能减少。</p>`;}
$('analyzeAll').onclick=async()=>{try{$('error').hidden=true;$('downloadAll').hidden=true;const mapping={};document.querySelectorAll('#mapping select').forEach(el=>mapping[el.dataset.category]=el.value);if(Object.values(mapping).includes('请选择'))throw Error('请先完成所有类别映射');setBusy(true,'逐月生成全部结果');const r=await api('/api/analyze-all',{body:JSON.stringify({rules:getRules(),mapping})});const f=await request({download:'all'});if(allUrl)URL.revokeObjectURL(allUrl);allUrl=URL.createObjectURL(new Blob([f.bytes],{type:'application/zip'}));$('downloadAll').href=allUrl;$('downloadAll').download=f.name;$('downloadAll').textContent='下载 '+r.months+' 个月的结果包';$('downloadAll').hidden=false;}catch(e){fail(e)}finally{setBusy(false)}};
